# to build manifest, run the following, followed by rsconnect::writemanifest(".")
#source("https://raw.githubusercontent.com/joey711/shiny-phyloseq/master/install.R")
# we have the library calls re-listed below to ensure they get tracked in said manifest

library(phyloseq)
library(biomformat)
library(shiny)
library(shinythemes)
library(ggplot2)
library(networkD3)
library(genefilter)
library(grid)
library(gridExtra)
library(markdown)
library(rmarkdown)
library(png)
library(RColorBrewer)
library(ggplot2)
#library(GenomeInfoDb)
library(scales)
print("sourcing globals")
source("global.R")
shinyAppDir(".")
